USE 'dma';
DROP procedure IF EXISTS `dma_student_reg`;

DELIMITER $$
USE 'dma';
CREATE PROCEDURE `dma_student_reg`(
USERID DOUBLE,
PASSWORD VARCHAR(45),
FIRSTNAME CHAR(100),
LASTNAME CHAR(100),
ADDRESS VARCHAR(45),
PHONE VARCHAR(45),
EMAILID VARCHAR(45),
ROLE CHAR(15),
COURSE VARCHAR(45),
BRANCH VARCHAR(45),
SESSION VARCHAR(45),
SECTION VARCHAR(45),
ATTENDANCE INT
)
BEGIN
INSERT INTO dma.dma_user_student VALUES (USERID, 
PASSWORD ,
FIRSTNAME ,
LASTNAME ,
ADDRESS ,
PHONE ,
EMAILID, 
ROLE ,
COURSE,
BRANCH ,
SESSION,
SECTION,
ATTENDANCE );
END$$
DELIMITER ;
