USE 'dma';
DROP procedure IF EXISTS `dma_staff_reg`;

DELIMITER $$
USE 'dma';
CREATE PROCEDURE `dma_staff_reg`(
USERID DOUBLE,
PASSWORD VARCHAR(45),
FIRSTNAME CHAR(100),
LASTNAME CHAR(100),
ADDRESS VARCHAR(45),
PHONE VARCHAR(45),
EMAILID VARCHAR(45),
ROLE CHAR(15),
TEACHESIN VARCHAR(45),
SUBJECTS VARCHAR(45),
WORKING VARCHAR(45)

)
BEGIN
INSERT INTO dma.dma_user VALUES (USERID, 
PASSWORD ,
FIRSTNAME ,
LASTNAME ,
ADDRESS ,
PHONE ,
EMAILID, 
ROLE ,
TEACHESIN,
SUBJECTS ,
WORKING);
END$$
DELIMITER ;
